id: refactor_with_state
hints: 
  - You can use `useState` to [keep the component state updated](https://reactjs.org/docs/hooks-state.html).
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Now we can refactor an entire component along with its state. Please **modify `CommentInput.js` to use Hooks** and then **open another PR**.
        delay: 1500
githubActions:
  frontend:
    testFile: commentInputFunctionalComponent.test.js
    cmd: yarn test --ci --watchAll=false --silent
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: I'll review the changes right away.
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: I'll review the changes right away.
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Excellent job ${user.firstName}! You can now merge the PR.
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Woohoo! Excellent job @${user.githubuser}! You can now merge the PR.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Nope, something's not right. Check your code, then please try again.
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Nice try, but it looks like the unit test failed. Can you check what went wrong?
        github_pr_merged:
          do:
          - actionId: finish_step
