id: refactor_with_state
hints: 
  - Just remember that you can use `useState` to [keep the component state updated](https://reactjs.org/docs/hooks-state.html).
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Looking good! Now we can refactor an entire component along with its state.
        delay: 2200
      - text:  Please :instruction[o**modify `CommentInput.js` to use Hooks] and then **open another PR**.
        delay: 1800
githubActions:
  frontend:
    testFile: commentInputFunctionalComponent.test.js
    cmd: yarn test --ci --watchAll=false --silent
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Thanks, I'll review the changes right away.
                delay: 2000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Thanks, I'll review the changes right away.
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Excellent job ${user.firstName}! Go ahead and merge the PR.
                delay: 2500
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Excellent job @${user.githubuser}! Go ahead and merge the PR.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: I appreciate you trying, but I less appreciate you failing. Check your code, then try again.
                delay: 3500
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: I appreciate you trying, but I less appreciate you failing. Can you check what went wrong?
        github_pr_merged:
          do:
          - actionId: finish_step
