id: refactor_simple
hints:[]
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Hey there! There’s an old React app we need to update, but something happened to its original developers. 
        delay: 1700
      - text: It’s not that the company doesn’t know what happened to them. Believe me, we know all too well—I just found one of the miniature armadillos from that incident a few days ago. But I digress. The point is that they’re not with us any longer. Before our teams begin resurrecting that app, we need you to go over it and refactor it. Mostly, that means you’ll need to use Hooks. 
        delay: 2500
      - text: Let's start with the header component. Please **refactor the code to use Hooks** and **open a PR** when you’re done!
        delay: 1000
githubActions:
  frontend:
    capabilities:
      - yargs
    testFile: functionalComponent.test.js
    cmd: yarn test --ci --watchAll=false --silent --component=./components/Header.js
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Neat, let me review your PR. 
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Saw your PR, reviewing it now. 
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Perfect, you can merge the PR now and we’ll continue.
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Great work. Go ahead and merge the PR.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Hmmm, looks like there’s a problem here. Can you go over the code again?
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Seems like there might be a problem with your code. Can you take a second look?


        github_pr_merged:
          do:
          - actionId: finish_step
