id: refactor_simple
hints: 
  -  Umm, you should probably try to follow the "[Introducing Hooks](https://reactjs.org/docs/hooks-intro.html)" guide and convert the class into a function.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Hi again, lovely weather outside, isn't it?   
        delay: 2500
      - text: Yes, great, wonderful, good. Anyway, there's an old React app we need to update, to make it easier to reuse stateful logic between components.
        delay: 4000
      - text: That’s why we decided to use [Hooks](https://reactjs.org/docs/hooks-intro.html#motivation)
        delay: 3200
      - text: https://media.giphy.com/media/B4ZgcoPTHYXL2/giphy.gif 
        delay: 4200
      - text: Let's start with something small - [refactoring a single class component into a functional component](https://reactjs.org/docs/hooks-overview.html).
        delay: 3500
      - text: So please :instruction[refactor the code in the `Header.js` component] to make it a functional component and **open a PR** when you’re done!
        delay: 1500
githubActions:
  frontend:
    testFile: headerIsFunctionalComponent.test.js
    cmd: yarn test --ci --watchAll=false --silent
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Give me a minute to review your PR. 
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Saw your PR, reviewing it now. 
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Perfect, you can merge the PR now and we’ll continue.
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Great work. Go ahead and merge the PR.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Hmmm, looks like there’s a problem here. Can you go over the code again?
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Seems like there might be a problem with your code. Can you take a second look?


        github_pr_merged:
          do:
          - actionId: finish_step
