id: refactor_with_state
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "On to the next order of business- please **modify `CommentInput.js` to make it a functional component**, and then **open another PR**."
        delay: 1500
githubActions:
  frontend:
    cmd:
      - CI=true yarn test
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: "I'll review the changes right away."
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: "I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: "Woohoo! Excellent job @${user.githubuser}! You can now merge the PR."
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: "Woohoo! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: "Something's not right. Check your code, then try again please."
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: "Hmm... Looks like the unit test failed. Can you check what went wrong?"
        github_pr_merged:
          do:
          - actionId: finish_step
