id: refactor_with_state
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: So the app’s code already uses Hooks, which is great. But what about that CommentInput.js? Now that we have Hooks, it can become a functional component. So please **modify `CommentInput.js` to make it a functional component** and then **open another PR**.
        delay: 1500
githubActions:
  frontend:
    capabilities:
      - yargs
    testFile: functionalComponent.test.js
    cmd: CI=true yarn test --component=./components/Item/CommentInput.js
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: I'll review the changes right away.
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: I'll review the changes right away.
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Excellent job @${user.githubuser}! You can now merge the PR.
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Woohoo! Excellent job ${user.firstName}! You can now merge the PR.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Nope, something's not right. Check your code, then please try again.
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Nice try, but it looks like the unit test failed. Can you check what went wrong?
        github_pr_merged:
          do:
          - actionId: finish_step
